plugins {
    alias(libs.plugins.fabric.loom)
}

base {
    archivesName = project.properties["archives_base_name"]
    version = libs.versions.mod.version.get()
    group = project.properties["maven_group"]
}

repositories {
    maven {
        name = "meteor-maven"
        url = uri("https://maven.meteordev.org/releases")
    }
    maven {
        name = "meteor-maven-snapshots"
        url = uri("https://maven.meteordev.org/snapshots")
    }
}

dependencies {
    minecraft libs.minecraft
    mappings loom.officialMojangMappings()
    modImplementation libs.fabric.loader
    modImplementation libs.meteor.client
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(libs.versions.jdk.get().toInteger())
    }
}

processResources {
    def propertyMap = [
        "version"          : project.version,
        "minecraft_version": "~1.21",
        "jdk_version"      : libs.versions.jdk.get()
    ]
    inputs.properties(propertyMap)
    filesMatching("fabric.mod.json") {
        expand(propertyMap)
    }
}

jar {
    inputs.property("archivesName", project.base.archivesName.get())
    from("LICENSE") {
        rename { "${it}_${inputs.properties["archivesName"]}" }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs.addAll(["-Xlint:deprecation", "-Xlint:unchecked"])
}
